version: 2.1

commands:
  setup-env:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: lein with-profile -dev,+test,+ci deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

executor_defaults: &executor_defaults
  working_directory: ~/repo

executors:
  openjdk8:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    <<: *executor_defaults
  openjdk8-node:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    <<: *executor_defaults
  openjdk11:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m --illegal-access=deny
    <<: *executor_defaults

jobs:
  test_code:
    description: |
      Runs tests against given version of the JDK
    parameters:
      jdk_version:
        description: Version of the JDK to test against
        type: string
      lein_test_command:
        description: A Leiningen command that will run a test suite
        type: string
    executor: << parameters.jdk_version >>
    steps:
      - setup-env
      - run:
          command: << parameters.lein_test_command >>
  cloverage:
    executor: openjdk8
    steps:
      - setup-env
      - run:
          name: 'Run JVM tests, reporting coverage'
          command: lein with-profile -dev,+test,+ci trampoline cloverage --lcov --junit -o coverage/
      - store_test_results:
          path: ~/repo/coverage
      - store_artifacts:
          path: ~/repo/coverage
  test_cljs_code:
    executor: openjdk8-node
    steps:
      - setup-env
      - run:
          name: 'Compile ClojureScript test suite'
          command: lein with-profile -dev,+test do clean, cljsbuild once test
      - run:
          name: 'Run node.js tests'
          command: node target/out/tests.js
  deploy:
    executor: openjdk8
    steps:
      - setup-env
      - run:
          name: import GPG key
          command: echo -e "$GPG_KEY_V2" | gpg --import
      - run:
          name: Perform pre-release sanity check
          command: lein with-profile -dev,+ci run -m nedap.ci.release-workflow.api sanity-check
      - run:
          name: release to JFrog
          command: lein deploy
      - run:
          name: release to Clojars
          command: lein deploy clojars          

test_code_filters: &test_code_filters
  filters:
    branches:
      only: /.*/
    tags:
      only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/

workflows:
  version: 2.1
  CircleCI:
    jobs:
      - test_code:
          name: "Ensure artifact isolation, inform of boxed math"
          jdk_version: openjdk8
          lein_test_command: lein with-profile -dev,+check check
          context: JFrog
          <<: *test_code_filters
      - cloverage:
          requires:
            - "Ensure artifact isolation, inform of boxed math"
          context: JFrog
          <<: *test_code_filters
      - test_cljs_code:
          context: JFrog
          <<: *test_code_filters
      - test_code:
          name: "JDK 8, plain"
          jdk_version: openjdk8
          lein_test_command: lein with-profile -dev,+ci do clean, test
          requires:
            - "Ensure artifact isolation, inform of boxed math"
            - cloverage
          context: JFrog
          <<: *test_code_filters
      - test_code:
          name: "JDK 8, with production-like compiler flags"
          jdk_version: openjdk8
          lein_test_command: lein with-profile -dev,+ci,+production do clean, test
          requires:
            - "Ensure artifact isolation, inform of boxed math"
            - cloverage
          context: JFrog
          <<: *test_code_filters
      - test_code:
          name: "JDK 11, plain"
          jdk_version: openjdk11
          lein_test_command: lein with-profile -dev,+ci,+jdk11 do clean, test
          requires:
            - "Ensure artifact isolation, inform of boxed math"
            - cloverage
          context: JFrog
          <<: *test_code_filters
      - test_code:
          name: "JDK 11, with production-like compiler flags"
          jdk_version: openjdk11
          lein_test_command: lein with-profile -dev,+ci,+jdk11,+production do clean, test
          requires:
            - "Ensure artifact isolation, inform of boxed math"
            - cloverage
          context: JFrog
          <<: *test_code_filters
      - deploy:
          context: JFrog
          requires:
            - "Ensure artifact isolation, inform of boxed math"
            - test_cljs_code
            - cloverage
            - "JDK 8, plain"
            - "JDK 8, with production-like compiler flags"
            - "JDK 11, plain"
            - "JDK 11, with production-like compiler flags"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
